# Generated by Django 5.1.4 on 2025-01-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '__first__'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateField()),
                ('km_atual', models.PositiveIntegerField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.BooleanField(default=False)),
                ('data_fim', models.BooleanField(default=False)),
                ('pendencias', models.TextField(blank=True, help_text='Informe pendências como Multa ou Manutenção', null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorista.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
        ),
    ]
