# Generated by Django 5.1.4 on 2025-01-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Desconhecido', max_length=50)),
                ('modelo', models.CharField(default='Desconhecido', max_length=50)),
                ('ano', models.IntegerField()),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('combustivel', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('km_atual', models.CharField(max_length=20)),
                ('cambio', models.CharField(max_length=50)),
            ],
        ),
    ]
