# Generated by Django 5.1.4 on 2025-01-27 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateField()),
                ('locadora', models.CharField(blank=True, max_length=20)),
                ('descricao_manutencao', models.TextField()),
                ('valor_manutencao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_manutencao', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=20)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motorista.motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.veiculo')),
            ],
        ),
    ]
